## Basic Configuration
baseurl = "https://krossovochkin.com/"
languageCode = "en"

title = "Vasya Drobushkov"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
googleAnalytics = "UA-148934073-1"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Vasya Drobushkov"
    title = "Krossovochkin"
    themeColor = "theme-base-0a"
    # description = "..."
    authorimage = "../img/avatar.png"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    #logoimage = "/img/hugo.png"
    copyright = "Vasya Drobushkov"
    since = 2019
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "androidstudio"
    highlightjslanguages = ["bash", "java", "kotlin"]
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "krossovochkin"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "vasyadrobushkov"
    twitter = "krossovochkin"
    facebook = "vasya.drobushkov"
    #microblog = "<username>"
    stackoverflow = "1533933/krossovochkin"
    telegram = "krossovochkin_newsletter"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    #email = "your-email@example.com"
    # gravatar = "your-email@example.com"
    # pgpkey = "<path-to-your-key-in-/static>"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"