name: Deploy

on:
  push:
    branches: "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout
        run: git submodule update --init --recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.140.1'
          extended: true
      - name: Deploy
        run: |
          chmod +x deploy.sh
          ./deploy.sh "${{ secrets.USER_GITHUB_TOKEN }}"
