name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: git submodule update --init --recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true
      - name: Deploy
        run: |
          git config --global user.email "ci@github"
          git config --global user.name "GitHub Actions CI"
          
          chmod +x deploy.sh
          ./deploy.sh "${{ secrets.GITHUB_TOKEN }}"
