name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< ${{secrets.SSH_KEY}}
      - name: Deploy
        run: |
          git submodule update --init --recursive
