name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start SSH agent
        run: eval $(ssh-agent -s)
      - name: Setup SSH key
        run: ssh-add - <<< "${{secrets.SSH_KEY}}"
      - name: Deploy
        run: git submodule update --init --recursive
